# -*- coding: utf-8 -*-
"""calculadora digital!

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BKtzOS8O1eWTZzbYXklrGUp2ZoVypF3-
"""

num1 = float(input("digite o primeiro numero: "))
num2 = float(input("digite o segundo numero: "))


print("\n Escolha a operações:")
print("1: Soma")
print("2: Subtração")
print("3: Multiplicação")
print("4: divisão")

opcao = int(input("Digite sua opção (1/2/3/4)\n"))

if opcao == 1:
    soma = (num1 + num2)
    print("resultado é", soma)

elif opcao == 2:
    subtracao = (num1 -num2)
    print("resultado é", subtracao)

elif opcao == 3:
    mult =(num1 * num2)
    print("resultado é", mult)

elif opcao == 4:
  if num2 != 0:

    div =(num1 / num2)
    print(" resultado é", div)
else:
    print("erro: Divisão por zero não é permitida:")